name: Update READMEs

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main
  workflow_dispatch:  # Allows manual execution from GitHub Actions tab

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Debug TOKEN
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "TOKEN is missing!"
            exit 1
          else
            echo "TOKEN is set!"
          fi

      - name: Run script to update READMEs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Using 'TOKEN' as the secret
        run: python generate_readmes.py
